name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  format-and-test:
    name: Format and unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: '1.23.x'

      - name: Verify formatting
        run: |
          set -euo pipefail
          GO_FILES=$(git ls-files '*.go')
          if [ -z "${GO_FILES}" ]; then
            echo "No Go files tracked; skipping gofmt check."
            exit 0
          fi
          UNFORMATTED=$(gofmt -l ${GO_FILES})
          if [ -n "${UNFORMATTED}" ]; then
            echo "The following files require gofmt:" >&2
            echo "${UNFORMATTED}" >&2
            exit 1
          fi

      - name: Run unit tests
        run: |
          set -euo pipefail
          go test ./...
